version: '3'

services:
    redis:
        container_name: redis
        image: redis:alpine
        volumes:
            - ./data/redis:/data
            - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
            - "6379:6379"
        networks:
            - common
        restart: always

    mysql:
        container_name: mysql
        image: mysql:8.0.27

        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: api
            MYSQL_DATABASE: main
            MYSQL_USER: api
            MYSQL_PASSWORD: api
        ports:
            - 3306:3306
        networks:
            - common
        restart: always

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - '8888:80'
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        depends_on:
            - mysql
        networks:
            - common
        restart: always

networks:
    common:
